# Generated by Django 4.1.4 on 2022-12-22 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='osoba_napomena',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.napomena'),
        ),
    ]
