# Generated by Django 4.1.4 on 2022-12-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_osoba_osoba_napomena'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrok',
            name='obrok_namirnice',
            field=models.ManyToManyField(default=None, to='main.namirnica'),
        ),
    ]
