# Generated by Django 4.1.4 on 2022-12-22 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_obrok_obrok_od_osobe'),
    ]

    operations = [
        migrations.AddField(
            model_name='datum',
            name='datum_obroka',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.obrok'),
        ),
    ]
