# Generated by Django 4.1.4 on 2022-12-23 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_napomena_napomena_alergije_napomena_napomena_bolesti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='napomena',
            name='napomena_alergije',
        ),
        migrations.RemoveField(
            model_name='napomena',
            name='napomena_bolesti',
        ),
    ]
